name: triton_server
services:
  triton_server:
    build:
      context: ../../
      dockerfile: deployment/dev/triton_server/Dockerfile
      args:
        MODEL_NAME: vit_base_patch16_384
        VERSION: 1
        BACKEND: pytorch
    image: triton_server_image
    container_name: triton_server_container
    volumes:
      - ./triton_server/image_classifier/config.json:/app/image_classifier/config.json
      - ./triton_server/preprocessor/config.json:/app/preprocessor/config.json
    ports:
        - "8000:8000"
        - "8001:8001"
        - "8002:8002"

  streamlit_app:
    build:
      context: ../../
      dockerfile: deployment/dev/ui/Dockerfile
    image: streamlit_app_image
    container_name: streamlit_app_container
    environment:
      - INFERENCE_SERVER=triton_server:8000
    ports:
      - "8501:8501"
    depends_on:
      - triton_server